### ISSUE TITLE
can it work on a Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [mefistotelis/swars#1]
im seeing if i can get this to work on my Pi4 with depain/buster
when i run the configure it says only work on i386

im thinking its a no since this is a old port

**Comment by mefistotelis** [comment]
The source has a lot of x86 asm.
Unless you have circa 2 years to rewrite all that to C, this stays as x86-only.

**Comment by Exarkuniv** [comment]
i did think it was a long shot, but still wanted to ask. 
thanks
