### ISSUE TITLE
Music from files does not work

### ISSUE THREAD

**Issue by geist22** [mefistotelis/swars#23]
I've compiled a fresh version from source.

My music files are:
```
Syndicate Wars\music\track_1.ogg
Syndicate Wars\music\track_2.ogg
Syndicate Wars\music\track_3.ogg
```
but they don't play. It worked in older versions of the port with the same files and structure, so this could be a more recent regression.

**Comment by mefistotelis** [comment]
Yeah, some of the port changes were hacks - we didn't had as much symbols then that we have now from PlayStation Beta.

I re-added their music init. Later we will remove it again, when the OGG music setup is merged with CD audio API.

**Comment by geist22** [comment]
Yup, works :)
