### ISSUE TITLE
Invisible weapon effects

### ISSUE THREAD

**Issue by geist22** [mefistotelis/swars#28]
Sometimes part of the effects produced by weapons such as the Plasma Lance or Pulse Laser appear invisible. It doesn't happen all the time, but relatively often. Don't know what triggers it.

Here's an example screenshot with the Plasma Lance, you can see the lines on the outside, but the main beam is invisible. 

![plasma_lance](https://user-images.githubusercontent.com/107389189/180625276-6c689dbe-0148-4a51-8179-bf367ad337cd.jpg)

**Comment by mefistotelis** [comment]
Maybe the rendering array gets filled?

Did that happen in original games as well, or only in port?

**Comment by geist22** [comment]
This doesn't happen in the original. I've also tried an older version of the port, although from a different source (based on 3.1.0) and it doesn't happen there either. Probably a more recent regression.

**Comment by mefistotelis** [comment]
Yeah, I can see it. It's enough to shoot several times with Plasma Lance to see it.

I am currently rewriting the rendering, so I thought it's just a mistake there. But when I switch back to the original assembly code, I see the issue as well.

This needs to be bisected to figure out when it started.

**Comment by mefistotelis** [comment]
Bisected the issue.
It started at commit `swars: Using first function from the static lib`.

**Comment by mefistotelis** [comment]
Workarounded with commit: [swars: Restored the old assembly code for square root](https://github.com/mefistotelis/swars/commit/a77a2a0a924383d7dc920efab9bd76d9ec4ea909).
