### ISSUE TITLE
bug: Pressing 'R' to restart during the game starts with default loadout

### ISSUE THREAD

**Issue by mefistotelis** [mefistotelis/swars#4]
The bug is not in original game.

Restarting the game with 'R' spawns the agents/zealots with default weapons for that level, rather than weapons bought by the player.

**Comment by Moburma** [comment]
Just to expand on the above, it seems once the R key is pressed once in-mission, it affects EVERY level played in that game session, not just the current one.
That is to say, if you quit the mission and start again, you willl have default equipment. 
If you load another saved game, you will default equipment. 
If you start an entirely new game, you will have default equipment.
The only way to have the equipment you have purchased and for the game to work properly again is to close the program and start all over again.

**Comment by mefistotelis** [comment]
Rewriting `do_user_interface()` would help in tracking that bug.
It is quite irritating, as restarting mission is used very often while playing.

**Comment by mefistotelis** [comment]
The issue seem to be that `ingame.GameMode` is not set properly - it is zero. On level restart, the value is "fixed" to 2. This causes the strange behavior.
The proper value while playing a campaign should be 3 - and that value is set when launching the game with '-g' command line option.

So the issue can be easily fixed by just running the game with correct command line options. But what each value of `ingame.GameMode` means - I still have no idea.

It is not a good practice to make the game work with issues if run without options. It should either use best options as default, or refuse to run completely (or in other way make it obvious) when started without options.

**Comment by stephematician** [comment]
PLAY.BAT (as installed from the GOG version - unsure about original) has the command "main /w /g" - is there documentation on those command arguments?

**Comment by mefistotelis** [comment]
> is there documentation on those command arguments?

Now there is:
https://github.com/mefistotelis/swars/commit/b734e5000072dcf7029d83880d5b3299283b3908

I also made automatic switching to mode 3 if no parameters were provided to override the mode:
https://github.com/mefistotelis/swars/commit/c226903d34639f36318cf158883a068c60783f85

So, this closes the issue. If run without params, the game will enter mode 3. Mode 1 can be activated with `-A`, mode 2 with `-m <num>`.
