### ISSUE TITLE
Configure script on Ubuntu 22.04 prints "python executable not found"

### ISSUE THREAD

**Issue by Dartomic** [mefistotelis/swars#5]
It's called python3 in this version of Ubuntu. Not sure if that's what the problem is.

**Comment by mefistotelis** [comment]
Python is detected in `configure.ac`, using:

```
AM_PATH_PYTHON([3.1])
```

If it doesn't check all binaries, you might try setting `_AM_PYTHON_INTERPRETER_LIST` before that call.

Note: I didn't tested Linux builds for some time, so expect more issues.

**Comment by Dartomic** [comment]
I fixed it before I saw this message by changing all occurrence of python to python3 in all of the files, without changing it in the mkwrappers script.

**Comment by Dartomic** [comment]
_AM_PYTHON_INTERPRETER_LIST doesn't exist in the configure script.
