### ISSUE TITLE
Start window centered

### ISSUE THREAD

**Issue by geist22** [mefistotelis/swars#50]
It would be great if, when playing in windowed mode, the window could always start in the center of the screen.

Such a small thing makes such a big difference in quality of life.

**Comment by mefistotelis** [comment]
This doesn't require code change, SDL provides such functionality. Just set env variable  `SDL_VIDEO_CENTERED=1`.

Linux:
```
SDL_VIDEO_CENTERED=1 ./swars -w -g
```

Windows:
```
set SDL_VIDEO_CENTERED=1
swars.exe /w /g
```

**Comment by geist22** [comment]
Thanks, I didn't know that.
