### ISSUE TITLE
Bug: While it is possible to choose between two different Tension music tunes, only one ever plays

### ISSUE THREAD

**Issue by Moburma** [mefistotelis/swars#52]
This is an original game bug. The game offers two tension music choices in the Audio menu. However, regardless of which is chosen, only the first ever plays. The Japanese version of the game plays a different tune if Trk2 is chosen (it's the song called "DANGER0.MID" on the page here: https://tcrf.net/Syndicate_Wars_(DOS)#Unused_Music), so presumably that song was what was intended to play as an alternative originally. 
As a potential enhancement there are also other unused tension songs in MUSIC.DAT (although they may have been intended for different soundcards/sound fonts as they are the same basic tunes but with different instruments playing them) that could perhaps be selectable by a config option.

**Comment by mefistotelis** [comment]
> there are also other unused tension songs in MUSIC.DAT

There are total of 6 MIDI files in that bank, but from how the game behaves, this seem to only be versions of the two songs for various MIDI devices.

Most cards have the same Yamaha chip which set MusicType="f". The more advanced MPU401 like cards (Soundscape,Gravis Ultradound) stores MusicType="g", MT32 stores "r" and the queen AWE32 sets MusicType="w" (this also enables some additional audio features but I don't know what they do, in DK this loads sound banks (SBK), but I don't think SW has these).

Then for the sound banks selection: "f"->0, "r"->1, "g"->2, "w"->3.

You may notice that there don't seem to be MIDI files for "w" - I don't know how that works.

**Comment by mefistotelis** [comment]
I fixed that (changed assembly, as this is not yet remade).
Though the instrument need to be added for that 2nd track.

**Comment by mefistotelis** [comment]
Added a 2nd track instrument. Confirmed that both tracks work.
(hopefully I will not forget about that change when rewriting `init_level` where I changed the asm)
