### ISSUE TITLE
Bugged models on research screen

### ISSUE THREAD

**Issue by geist22** [mefistotelis/swars#62]
This started happening recently, I think during the changes to formats for the old unguided levels: 

![research](https://github.com/mefistotelis/swars/assets/107389189/a00885c2-3c17-4a6a-bfeb-bf8453c99b20)

When the animation starts, you get to see the upper body, but the rest stays like this.

**Comment by mefistotelis** [comment]
Hm, that works for me.. I mean:
1. Started new Eurocorp game, bought V1 mods - all displayed fine
2. Loaded a Church game, looked at my V3 mods - all displayed fine

Are you sure you're got `ProjectorFnMk = "s"` in mission config file? If it was unset and so related files could not be found, the results would be similar.

If that's not it - please provide repro steps.

**Comment by geist22** [comment]
I've copied the config files from the latest artifacts so they should be identical. `ProjectorFnMk = "s"` line is there.

Just tried with slow projector speed and it looks normal. It only happens with projector speed set to fast, which is what I use in my savegames.

**Comment by Moburma** [comment]
Confirmed for me as well. I've only got savedgames with level 3 implants installed, but if I load one of them up, and the game is in fast projector mode it's corrupted as above screenshot. Works fine if projector is set to slow.

**Comment by mefistotelis** [comment]
Right, I'm guilty of using slow projector.

I have the repro now.

**Comment by mefistotelis** [comment]
Should be fixed now.

**Comment by geist22** [comment]
Seems to work.
