### ISSUE TITLE
Some missions don't end the game if aborted

### ISSUE THREAD

**Issue by geist22** [mefistotelis/swars#63]
When quitting a non-optional mission from the pause screen, the game normally ends in a game over. Only in optional missions (EuroCorp mission 3 and 10) you're sent back to try again.

However some missions are bugged now. If you quit them, you don't get a game over and instead get sent back like for optional missions, but the mission disappears and you'll get the next one as if it was completed successfully. All other missions under the same mission number are then gone too.

The bugged missions are:

EuroCorp Mission 7: Hong Kong (skips Beijing and Phoenix)
EuroCorp Mission 12: Reykjavik (skips follow-up in Nuuk)
EuroCorp Mission 14: Tokyo (skips follow-up in Bangkok)
EuroCorp Mission 18: New Delhi (skips Sevastopol)

**Comment by mefistotelis** [comment]
Ha, and I though I was being smart by being able to simplify `delete_open_mission()`..
Guess that convoluted code really did something.

**Comment by mefistotelis** [comment]
My simplification seem correct, I just made a mistake and called success trigger instead of fail in one of the cases..
Should be fixed now.
